name: Wiz Risk Issue Test

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  wiz-risk-test:
    runs-on: ubuntu-latest
    steps:
      - name: Harmless test
        run: echo "Wiz GitHub Actions risk test"
